import { EventEmitter, OnInit, TemplateRef, OnDestroy } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { DialogService } from '../dialog';
import { DateTimeType } from './date-time.type';
export declare class DateTimeComponent implements OnInit, OnDestroy, ControlValueAccessor {
    private dialogService;
    id: string;
    name: string;
    disabled: boolean;
    tabindex: number;
    autofocus: boolean;
    label: string;
    hint: string;
    placeholder: string;
    minDate: Date;
    maxDate: Date;
    format: string;
    inputType: DateTimeType;
    change: EventEmitter<{}>;
    value: any;
    calendarTpl: TemplateRef<any>;
    _value: any;
    errorMsg: string;
    dialog: any;
    dialogModel: any;
    hour: any;
    minute: any;
    amPmVal: any;
    constructor(dialogService: DialogService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    writeValue(val: any): void;
    open(): void;
    apply(): void;
    dateSelected(date: any): void;
    minuteChanged(newVal: any): void;
    hourChanged(newVal: any): void;
    selectCurrent(): void;
    clear(): void;
    onAmPmChange(newVal: any): void;
    getDayDisabled(date: any): boolean;
    inputChanged(val: any): void;
    close(): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    private onTouchedCallback;
    private onChangeCallback;
}
