language: node_js

node_js:
  - 'node'

cache:
  directories:
    - ~/.npm
    - ~/.cache

addons:
  chrome: stable
  apt:
    packages:
      - libgconf-2-4

services:
  - xvfb

before_install:
  - export NG_CLI_ANALYTICS=ci

install:
  - npm install
  - npm run build
  - npm run build:lib

script:
  - npm run ci
