language: node_js

node_js:
  - 12

cache:
  directories:
    - ~/.npm
    - ~/.cache
    - node_modules

addons:
  apt:
    packages:
    - libgconf-2-4

before_install:
  - export NG_CLI_ANALYTICS=ci

install:
  - npm ci
  - npm run build

script:
  - npm run ci
