module.exports = {
  projects: [
    '<rootDir>/packages/ngx-ui',
    '<rootDir>/packages/ngx-ui/typings',
    '<rootDir>/packages/ngx-ui/utils',
    '<rootDir>/packages/ngx-ui/common',
    '<rootDir>/packages/ngx-ui/animations',
    '<rootDir>/packages/ngx-ui/autosize-input',
    '<rootDir>/packages/ngx-ui/copy-to-clipboard',
    '<rootDir>/packages/ngx-ui/long-press',
    '<rootDir>/packages/ngx-ui/resize-observer',
    '<rootDir>/packages/ngx-ui/intersection-observer',
    '<rootDir>/packages/ngx-ui/camel-to-snake',
    '<rootDir>/packages/ngx-ui/decamelize',
    '<rootDir>/packages/ngx-ui/filter-by',
    '<rootDir>/packages/ngx-ui/json-tree',
    '<rootDir>/packages/ngx-ui/time-zone',
    '<rootDir>/packages/ngx-ui/button',
    '<rootDir>/packages/ngx-doc',
    '<rootDir>/packages/ngx-ui/file-button',
    '<rootDir>/packages/ngx-ui/calendar',
    '<rootDir>/packages/ngx-ui/card',
    '<rootDir>/packages/ngx-ui/checkbox',
    '<rootDir>/packages/ngx-ui/tooltip',
    '<rootDir>/packages/ngx-ui/code-editor',
  ],
};
