import { AfterViewInit, ChangeDetectorRef, EventEmitter, OnInit } from '@angular/core';
import { ControlValueAccessor, Validator, FormControl } from '@angular/forms';
import { InputTypes } from './input-types';
export declare class InputComponent implements OnInit, AfterViewInit, ControlValueAccessor, Validator {
    private cd;
    id: string;
    name: string;
    label: string;
    type: InputTypes;
    hint: string;
    placeholder: string;
    disabled: boolean;
    tabindex: number;
    min: number;
    max: number;
    minlength: number;
    maxlength: number;
    required: boolean;
    requiredIndicator: string | boolean;
    passwordToggleEnabled: boolean;
    passwordTextVisible: boolean;
    autoSelect: boolean;
    autofocus: boolean;
    autocomplete: boolean;
    autocorrect: boolean;
    spellcheck: boolean;
    change: EventEmitter<{}>;
    blur: EventEmitter<{}>;
    focus: EventEmitter<{}>;
    keyup: EventEmitter<{}>;
    click: EventEmitter<{}>;
    value: string;
    readonly getHostCssClasses: string;
    readonly focusedOrDirty: any;
    readonly isTouched: boolean;
    readonly labelState: string;
    readonly underlineState: string;
    readonly requiredIndicatorView: string;
    readonly element: any;
    focused: boolean;
    private _value;
    private inputControl;
    private inputModel;
    private textareaControl;
    private passwordControl;
    constructor(cd: ChangeDetectorRef);
    validate(c: FormControl): {
        [x: string]: any;
    };
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnChanges(changes: any): void;
    onChange(event: any): void;
    onKeyUp(event: any): void;
    onFocus(event: any): void;
    onBlur(event: any): void;
    writeValue(val: string): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    togglePassword(): void;
    private onTouchedCallback;
    private onChangeCallback;
}
