import { EventEmitter, OnInit } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
export declare class SliderComponent implements ControlValueAccessor, OnInit {
    id: string;
    min: number;
    max: number;
    step: number;
    orientation: string;
    filled: boolean;
    multiple: boolean;
    disabled: boolean;
    showTicks: boolean;
    tickStep: number;
    _values: number[];
    _percents: number[];
    _thumbs: any[];
    _fill: any;
    _ticks: any[];
    _active: any[];
    active: boolean;
    value: any;
    readonly percent: string;
    change: EventEmitter<{}>;
    readonly isHorizontal: boolean;
    readonly isVertical: boolean;
    setValues(values: number[]): void;
    setActive(index: number, active: boolean): void;
    ngOnInit(): void;
    setValue(val: number, index: number): void;
    getCount(): any;
    getTicks(): any;
    getFill(): any;
    onMouseDown(): void;
    onMouseUp(): void;
    onChange(event: any): void;
    writeValue(val: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    trackIndex(index: any): any;
    private onTouchedCallback;
    private onChangeCallback;
}
