const externalLibs = [
  '@angular/platform-browser-dynamic',
  '@angular/platform-browser',
  '@angular/core',
  '@angular/common',
  '@angular/forms',
  'core-js',
  'core-js/es6',
  'core-js/es7/reflect',
  'rxjs',
  'rxjs/Rx',
  'rxjs/Subscription',
  'zone.js/dist/zone',
  '@angular/animations',
  'rxjs',
  'codemirror',
  'codemirror/mode/yaml/yaml.js',
  'codemirror/mode/python/python.js',
  'codemirror/mode/powershell/powershell.js',
  'codemirror/mode/javascript/javascript.js',
  'codemirror/mode/htmlmixed/htmlmixed.js',
  'codemirror/mode/spreadsheet/spreadsheet.js',
  'codemirror/addon/lint/lint.js',
  'codemirror/addon/search/search.js',
  'codemirror/addon/search/searchcursor.js',
  'codemirror/addon/search/jump-to-line.js',
  'codemirror/addon/dialog/dialog.js',
  'codemirror/addon/fold/foldcode.js',
  'codemirror/addon/fold/foldgutter.js',
  'codemirror/addon/fold/indent-fold.js',
  'moment'
];

module.exports = externalLibs;
