/// <reference types="core-js" />
import { EventEmitter } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { DialogService } from '../dialog';
import { DateTimeType } from './date-time.type';
import './date-time.scss';
export declare class DateTimeComponent implements ControlValueAccessor {
    private dialogService;
    id: string;
    name: string;
    disabled: boolean;
    tabindex: number;
    autofocus: boolean;
    label: string;
    hint: string;
    placeholder: string;
    minDate: Date;
    maxDate: Date;
    format: string;
    inputType: DateTimeType;
    change: EventEmitter<{}>;
    value: any;
    private calendarTpl;
    private _value;
    private errorMsg;
    private dialog;
    private dialogModel;
    private amPmToggle;
    private hour;
    private minute;
    private timeEnabled;
    constructor(dialogService: DialogService);
    ngOnInit(): void;
    writeValue(val: any): void;
    open(): void;
    apply(): void;
    dateSelected(date: any): void;
    minuteChanged(newVal: any): void;
    hourChanged(newVal: any): void;
    selectCurrent(): void;
    clear(): void;
    toggleTime(): void;
    toggleAmPm(newVal: any): void;
    getDayDisabled(date: any): any;
    inputChanged(val: any): void;
    close(): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    private onTouchedCallback;
    private onChangeCallback;
}
